### ISSUE TITLE
Need CI-testing setup

### ISSUE THREAD

**Issue by Zodiase** [Zodiase/map-visualizer#1]

**Comment by Zodiase** [comment]
Reference: https://travis-ci.org/

**Comment by xhuang26** [comment]
currently considered automated testing tools:
phantomJS: a full WebKit; support many browser standards; headless on linux; but need more configurations
phantomJS + Selenium: cover more powerful testing cases if needed in the future
CasperJS: build on top of phantomJS, more light-weighted compared to phantomJS, high-level functions and methods for doing common tasks
ZombieJS: relies on emulator of DOM API, faster, light-weighted, limited scope, have trouble testing with OAUTH (might not be important for this map-visualizer though)
nightwatch.js

**Comment by xhuang26** [comment]
Reference:
phantomJS+Selenium: http://code.tutsplus.com/tutorials/headless-functional-testing-with-selenium-and-phantomjs--net-30545
ZombieJS testing OAUTH: http://blog.bandwidth.com/testing-oauth-integration-flows-with-zombie-js/
Phantom VS CasperJS vs Selenium: https://www.linkedin.com/pulse/choosing-automated-testing-frameworks-phantomjs-casperjs-agarwal

**Comment by xhuang26** [comment]
travis CI for headless browser testing: https://docs.travis-ci.com/user/gui-and-headless-browsers/
connecting travis CI with sauselab for remote webdriver: http://samsaccone.com/posts/testing-with-travis-and-sauce-labs.html

**Comment by xhuang26** [comment]
instead of using sauselab, just include "java -jar selenium-server-standalone-2.53.0.jar &" in tranvis.yml in order to run webdriver on tranvisCI ---works fine now

**Comment by xhuang26** [comment]
webdriverJS is deprecated, use webdriverIO instead: 
webdriverIO github: https://github.com/webdriverio/webdriverio#list-of-current-helper-methods
webdriverIO syntax: http://webdriver.io/guide/usage/selectors.html
syntax comparison between webdriverIO, selenium-webdriverjs and WD: https://github.com/webdriverio/webdriverio/issues/138

**Comment by xhuang26** [comment]
es6 environment with phantomjs: https://github.com/webdriverio/webdriverio/issues/1323
currently works fine for webdriverio + firefox. 
Phantomjs cannot fully support es6 without babel or karma
Trying to figure out how to make a way around it

**Comment by xhuang26** [comment]
good example of how to add custom command in webdriverio:
https://github.com/webdriverio/webdriverio/issues/429

**Comment by Zodiase** [comment]
I've added `eslint` and `babel-cli` and corresponding npm commands in this project for linting and transpiling es6 code to es5. @xhuang26 You might want to pull the changes and update your test setup. For example, use the transpiled code in `lib` folder (after running `npm run build`) for testing.

**Comment by Zodiase** [comment]
With the linter in place, you may now run `npm run lint` to see issues in `src/*.js` related to coding standards. You might also want to add another command, `npm run lint-test` for example, for linting your test files.

**Comment by xhuang26** [comment]
babel-polyfil: Symbol/Map in es6 can be understood
using babel-polyfill and phantomjs works fine now
