### ISSUE TITLE
map proportion incorrect

### ISSUE THREAD

**Issue by yanliu-chn** [Zodiase/map-visualizer#19]
the basemap and all the layers look compressed vertically. i doubled checked if this is due to diff projection, e.g., epsg:4326 or epsg:3857. But later I confirmed that it might be a bug.

[layers for HAND](http://141.142.168.44/nfiedata/maps/#source=..%2Fyanliu%2Fviz%2Fhuc6-mercator.json&extent=-128.3203125_22.1484375_-66.884765625_55.634765625) (web mercator basemap):

![image](https://cloud.githubusercontent.com/assets/4205485/16439909/79853a24-3d82-11e6-9f1a-3c4b2c6be8a8.png)

same layers on esri arcgis online (web mercator):

![image](https://cloud.githubusercontent.com/assets/4205485/16439869/ffdba2a8-3d81-11e6-9bb1-3527a29d1f9e.png)

**Comment by Zodiase** [comment]
This is not a bug as the same compression can be observed in this example:

EPSG: 4326
![image](https://cloud.githubusercontent.com/assets/1815174/16496627/7c47af8a-3eb8-11e6-8e71-6c8029e9113f.png)

EPSG: 3857
![image](https://cloud.githubusercontent.com/assets/1815174/16496625/74321e48-3eb8-11e6-9dd3-7ffa814fedfb.png)

**Comment by yanliu-chn** [comment]
This issue is resolved by allowing users to specify the map projection. The original implementation renders WGS84 only.
